version: "2"
services:
    app:
        image: mhart/alpine-node:12.3.1
        restart: always
        ports:
            - "3000:3000"
        working_dir: /my-app/src/app
        volumes:
            - ./my-app:/my-app/src/app
        entrypoint: ["npm", "start"]

