version: '2'
services:
  anaconda3-jupyter:
    container_name: anaconda3-jupyter
    restart: always
    build:
      context: .
    ports:
     - "8888:8888"
    environment:
     - disable_password={DISABLE_PASSWORD}
     - jupyter_password={JUPYTER_PASSWORD}
     - base_url='/'
    command: bash -c "python /root/configgen.py" 
    volumes:
     - ./notebooks:/opt/notebooks
